sonar.projectKey=certifypro-frontend
sonar.projectName=CertifyPro Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/.angular/**,**/dist/**,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info