sonar.projectKey=sirineee22_Esprit-PiProject-4SAE8-2026-CertifyPro
sonar.organization=sirineee22
sonar.projectName=CertifyPro Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
