create table if not exists roles (
  id bigint generated by default as identity primary key,
  name varchar(60) not null unique
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(50) not null unique,
  password varchar(120) not null,
  phone_number varchar(255),
  active boolean not null default true,
  role_id bigint references roles(id)  
  
);

insert into roles (name) values ('ADMIN') on conflict (name) do nothing;
insert into roles (name) values ('TRAINER') on conflict (name) do nothing;
insert into roles (name) values ('LEARNER') on conflict (name) do nothing;

insert into users (first_name, last_name, email, password, role_id, active)
select 'Admin', 'User', 'admin@platform.com', 'Admin123!', r.id, true
from roles r
where r.name = 'ADMIN'
on conflict (email) do nothing;
