version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server

  user-service:
    build: ./services/user-service
    ports:
      - "8883:8883"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  training-service:
    build: ./services/training-service
    ports:
      - "8086:8086"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  event-service:
    build: ./services/event-service
    ports:
      - "8884:8884"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/eventdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  ecommerce-service:
    build: ./services/ecommerce
    ports:
      - "8085:8085"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecommerce_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  forum-service:
    build: ./services/forum_service
    ports:
      - "8087:8086"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/forumdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  collaboration-service:
    build: ./services/collaboration-service
    ports:
      - "8088:8085"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  planned-session-service:
    build: ./services/planned-session-service
    ports:
      - "8084:8084"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - discovery-server
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
