pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        SONAR_TOKEN = credentials('sonar-token')
        SONAR_PROJECT_KEY = 'sirineee22_Esprit-PiProject-4SAE8-2026-CertifyPro'
        SONAR_ORG = 'sirineee22'
        IMAGE_NAME = 'siriinaa2233/certifypro-user-service'
        MAVEN_OPTS = '-Dmaven.repo.local=/var/jenkins_home/.m2/repository'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build, Test & SonarQube Analysis') {
            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            environment {
                DB_URL = 'jdbc:h2:mem:testdb'
                DB_USERNAME = 'sa'
                DB_PASSWORD = ''
                JWT_SECRET = 'test-secret-min-32-chars-for-testing-only'
            }
            steps {
                dir('backend/services/user-service') {
                    sh """
                        mvn verify sonar:sonar -B \
                            -Dspring.profiles.active=test \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.organization=${SONAR_ORG} \
                            -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.token=${SONAR_TOKEN} \
                            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                    """
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('backend/services/user-service') {
                    sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} -t ${IMAGE_NAME}:latest ."
                    sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                    sh "docker push ${IMAGE_NAME}:${BUILD_NUMBER}"
                    sh "docker push ${IMAGE_NAME}:latest"
                }
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
        }
        success {
            echo 'User Service pipeline succeeded!'
        }
        failure {
            echo 'User Service pipeline failed!'
        }
    }
}
