sonar.projectKey=sirineee22_Esprit-PiProject-4SAE8-2026-CertifyPro
sonar.organization=sirineee22
sonar.projectName=CertifyPro User Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/generated/**
