apiVersion: apps/v1
kind: Deployment
metadata:
  name: certifypro-frontend
  namespace: certifypro
  labels:
    app: certifypro-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certifypro-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: certifypro-frontend
    spec:
      containers:
        - name: certifypro-frontend
          image: nesrrine/certifypro-frontend:latest   # mis à jour par Jenkins CD
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: certifypro-frontend
  namespace: certifypro
  labels:
    app: certifypro-frontend
spec:
  selector:
    app: certifypro-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
