# ⚠️ NE PAS COMMITTER avec de vraies valeurs — utiliser des variables CI/CD
# Générer les valeurs base64 : echo -n "valeur" | base64
apiVersion: v1
kind: Secret
metadata:
  name: job-careers-secrets
  namespace: certifypro
type: Opaque
data:
  # echo -n "jdbc:postgresql://postgres:5432/job_db" | base64
  db-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9qb2JfZGI=
  # echo -n "postgres" | base64
  db-username: cG9zdGdyZXM=
  # echo -n "admin" | base64
  db-password: YWRtaW4=
  # echo -n "prod-secret-min-32-chars-certifypro-2026" | base64
  jwt-secret: cHJvZC1zZWNyZXQtbWluLTMyLWNoYXJzLWNlcnRpZnlwcm8tMjAyNg==
---
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secrets
  namespace: certifypro
type: Opaque
data:
  # echo -n "mongodb://mongodb:27017/messaging_db" | base64
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbWVzc2FnaW5nX2Ri
  # echo -n "prod-secret-min-32-chars-certifypro-2026" | base64
  jwt-secret: cHJvZC1zZWNyZXQtbWluLTMyLWNoYXJzLWNlcnRpZnlwcm8tMjAyNg==
