# ?? Serveur ??????????????????????????????????????????????????
server.port=8085

# ?? Nom du service pour Eureka ???????????????????????????????
spring.application.name=messaging-service

# ?? MongoDB ??????????????????????????????????????????????????
spring.data.mongodb.uri=mongodb://localhost:27017/messagingdb?authSource=admin
spring.data.mongodb.auto-index-creation=true

# ?? Désactiver JPA / SQL (MongoDB uniquement) ?????????????????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# ?? Eureka Client ????????????????????????????????????????????
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ?? JWT ??????????????????????????????????????????????????????
jwt.secret=dev-secret-min-32-chars-for-local-only

# ?? Upload fichiers ??????????????????????????????????????????
app.base-url=http://localhost:8085
app.upload.dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB

# ?? Logs ?????????????????????????????????????????????????????
logging.level.org.springframework=INFO
logging.level.com.esprit.pi=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
