name: Event Service CD

on:
  workflow_run:
    workflows:
      - "Event Service CI"
    types:
      - completed
    branches:
      - sirine-devops
      - main

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push event-service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/services/event-service
          file: ./backend/services/event-service/Dockerfile
          push: true
          tags: |
            siriinaa2233/certifypro-event-service:latest
            siriinaa2233/certifypro-event-service:${{ github.sha }}
