name: Frontend CI

on:
  push:
    branches:
      - sirine-devops
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-and-test:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Run unit tests
        working-directory: frontend
        run: npx ng test --no-watch

      - name: Build production
        working-directory: frontend
        run: npm run build -- --configuration production
