name: Frontend CI

on:
  push:
    branches:
      - sirine-devops
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-and-test:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Run unit tests with coverage
        working-directory: frontend
        run: npx ng test --no-watch --code-coverage
        continue-on-error: true

      - name: Build production
        working-directory: frontend
        run: npm run build -- --configuration production

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
          -Dsonar.projectKey=sirineee22_Esprit-PiProject-4SAE8-2026-CertifyPro
          -Dsonar.organization=sirineee22
          -Dsonar.sources=src
          -Dsonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
