name: User Service CD

on:
  push:
    branches:
      - sirine-devops
      - main
    paths:
      - 'backend/services/user-service/**'
      - '.github/workflows/user-service-cd.yml'

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push user-service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/services/user-service
          file: ./backend/services/user-service/Dockerfile
          push: true
          tags: |
            siriinaa2233/certifypro-user-service:latest
            siriinaa2233/certifypro-user-service:${{ github.sha }}
